<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5x2wOvd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5x2wOvd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5x2wOvd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5x2wOvd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5x2wOvd\App_KernelDevDebugContainer([
    'container.build_hash' => '5x2wOvd',
    'container.build_id' => '38d1ad51',
    'container.build_time' => 1589701244,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5x2wOvd');
